mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-爱在四月雪.mp3","Chunyy-爱在四月雪");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-安魂曲.mp3","Chunyy-安魂曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-安妮的歌.mp3","Chunyy-安妮的歌");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-宝贝珍之歌.mp3","Chunyy-宝贝珍之歌");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-沉睡的森林.mp3","Chunyy-沉睡的森林");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-沉思曲.wma","Chunyy-沉思曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-初恋的地方.mp3","Chunyy-初恋的地方");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-春之声圆舞曲 古典钢琴.mp3","Chunyy-春之声圆舞曲 古典钢琴");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-大溪地清流 米奴哀舞.wma","Chunyy-大溪地清流 米奴哀舞");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-第六感生死恋.wma","Chunyy-第六感生死恋");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-断情殇.mp3","Chunyy-断情殇");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-飞鼠溪.wma","Chunyy-飞鼠溪");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-风的气息.mp3","Chunyy-风的气息");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-风中之尘.mp3","Chunyy-风中之尘");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-格里格索尔维格之歌.mp3","Chunyy-格里格索尔维格之歌");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-和兰花在一起.wma","Chunyy-和兰花在一起");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-很好听.mp3","Chunyy-很好听");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-火宵之月.mp3","Chunyy-火宵之月");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-卡布里的月光.mp3","Chunyy-卡布里的月光");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-卡农钢琴曲.mp3","Chunyy-卡农钢琴曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-蓝色的爱.mp3","Chunyy-蓝色的爱");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-梁祝之化蝶 笛子.wma","Chunyy-梁祝之化蝶 笛子");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-绵雪.mp3","Chunyy-绵雪");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-茉莉花.mp3","Chunyy-茉莉花");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-森林中的一天.mp3","Chunyy-森林中的一天");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-似曾相识.wma","Chunyy-似曾相识");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-守护你的天使.mp3","Chunyy-守护你的天使");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-树蛙之歌.mp3","Chunyy-树蛙之歌");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-水之轮回.mp3","Chunyy-水之轮回");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-天鹅湖.mp3","Chunyy-天鹅湖");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-万福玛丽亚.mp3","Chunyy-万福玛丽亚");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-我的海洋.wma","Chunyy-我的海洋");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-西班牙斗牛士进行曲.mp3","Chunyy-西班牙斗牛士进行曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-西藏的月.mp3","Chunyy-西藏的月");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-昔日情怀.mp3","Chunyy-昔日情怀");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-夏日华尔兹.mp3","Chunyy-夏日华尔兹");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-乡间晚风.mp3","Chunyy-乡间晚风");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-相识也是缘份.mp3","Chunyy-相识也是缘份");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-小步舞曲.mp3","Chunyy-小步舞曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-小雨落在你脸上.mp3","Chunyy-小雨落在你脸上");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-雪之梦.mp3","Chunyy-雪之梦");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-野鸟情歌.mp3","Chunyy-野鸟情歌");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-印象之旅.mp3","Chunyy-印象之旅");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-雨林深处.mp3","Chunyy-雨林深处");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-雨中漫步.mp3","Chunyy-雨中漫步");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-月光下的凤尾竹.mp3","Chunyy-月光下的凤尾竹");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-云淡风轻.wma","Chunyy-云淡风轻");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-只此一生.mp3","Chunyy-只此一生");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Chunyy-最终幻想.mp3","Chunyy-最终幻想");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/Joanie madden-The level plain.mp3","Joanie madden-The level plain");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/yiruma-雨的印记.wma","yiruma-雨的印记");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/爱尔兰风笛 漫步神秘园.wma","爱尔兰风笛 漫步神秘园");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/爱尔兰口哨女皇madden-爱尔兰画眉.mp3","爱尔兰口哨女皇madden-爱尔兰画眉");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-chariots of fire.wma","班得瑞-chariots of fire");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-diamonds.mp3","班得瑞-diamonds");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-EI condor pasa.mp3","班得瑞-EI condor pasa");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-i want to know love is.mp3","班得瑞-i want to know love is");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-i_swear.wma","班得瑞-i_swear");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-imagine.mp3","班得瑞-imagine");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-into red velvet.wma","班得瑞-into red velvet");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-moment of fantasy.mp3","班得瑞-moment of fantasy");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-one moment in time.mp3","班得瑞-one moment in time");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-tenderness.mp3","班得瑞-tenderness");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-the sounds of silence.wma","班得瑞-the sounds of silence");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-tim's lullaby.wma","班得瑞-tim's lullaby");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-安妮的仙境.mp3","班得瑞-安妮的仙境");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-变幻之风.wma","班得瑞-变幻之风");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-晨光.wma","班得瑞-晨光");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-初雪.mp3","班得瑞-初雪");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-春水.wma","班得瑞-春水");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-春野.mp3","班得瑞-春野");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-春野.wma","班得瑞-春野");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-非洲日落.wma","班得瑞-非洲日落");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-风的呢喃.wma","班得瑞-风的呢喃");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-海王星.wma","班得瑞-海王星");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-火战车.mp3","班得瑞-火战车");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-涟漪.wma","班得瑞-涟漪");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-马可波罗.mp3","班得瑞-马可波罗");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-满天星.mp3","班得瑞-满天星");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-秘密.wma","班得瑞-秘密");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-排箫 老鹰之歌.wma","班得瑞-排箫 老鹰之歌");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-清晨.wma","班得瑞-清晨");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-日光海岸.mp3","班得瑞-日光海岸");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-天堂之门.wma","班得瑞-天堂之门");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-微风山谷.mp3","班得瑞-微风山谷");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-无止境的见识.wma","班得瑞-无止境的见识");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-夏日华尔兹.wma","班得瑞-夏日华尔兹");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-仙境.wma","班得瑞-仙境");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-依卡路斯的羽翼.mp3","班得瑞-依卡路斯的羽翼");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-忧郁的爱.mp3","班得瑞-忧郁的爱");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-月光 .WMA","班得瑞-月光 ");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-月光.mp3","班得瑞-月光");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-追梦人.mp3","班得瑞-追梦人");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班得瑞-紫蝴蝶.mp3","班得瑞-紫蝴蝶");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/班德瑞-巴格达的星星.mp3","班德瑞-巴格达的星星");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/贝多芬-悲怆奏鸣曲.mp3","贝多芬-悲怆奏鸣曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/贝多芬-命运交响乐.mp3","贝多芬-命运交响乐");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/贝多芬-田园交响曲.wma","贝多芬-田园交响曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/贝多芬-月光奏鸣曲.mp3","贝多芬-月光奏鸣曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/杜普雷-殇.mp3","杜普雷-殇");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/宫崎骏 龙猫-水晶音乐.mp3","宫崎骏 龙猫-水晶音乐");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/久石让-天空之城.mp3","久石让-天空之城");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/凯文柯恩-走过绿意.wma","凯文柯恩-走过绿意");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/浪客剑心-In Memories “A boy meets The Man”.mp3","浪客剑心-In Memories “A boy meets The Man”");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/李斯特-钟.mp3","李斯特-钟");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-爱的纪念.mp3","理查德 克莱德曼-爱的纪念");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-爱的协奏曲.mp3","理查德 克莱德曼-爱的协奏曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-爱之梦.wma","理查德 克莱德曼-爱之梦");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-出埃及记.mp3","理查德 克莱德曼-出埃及记");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-给母亲的信.wma","理查德 克莱德曼-给母亲的信");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-海边的祈祷.mp3","理查德 克莱德曼-海边的祈祷");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-海边的星空.wma","理查德 克莱德曼-海边的星空");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-欢乐颂.wma","理查德 克莱德曼-欢乐颂");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-欢乐之歌.wma","理查德 克莱德曼-欢乐之歌");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-蓝色的爱.mp3","理查德 克莱德曼-蓝色的爱");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-蓝色狂想曲.wma","理查德 克莱德曼-蓝色狂想曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-罗密欧与朱丽叶.wma","理查德 克莱德曼-罗密欧与朱丽叶");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-玫瑰色的人生.mp3","理查德 克莱德曼-玫瑰色的人生");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-梦中的婚礼.mp3","理查德 克莱德曼-梦中的婚礼");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-梦中的鸟.mp3","理查德 克莱德曼-梦中的鸟");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-秘密的庭院.mp3","理查德 克莱德曼-秘密的庭院");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-乒乓之恋.wma","理查德 克莱德曼-乒乓之恋");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-秋日私语.mp3","理查德 克莱德曼-秋日私语");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-柔如彩虹.wma","理查德 克莱德曼-柔如彩虹");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-伤感乐曲.wma","理查德 克莱德曼-伤感乐曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-少女的祈祷.wma","理查德 克莱德曼-少女的祈祷");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-水边的阿狄丽娜.mp3","理查德 克莱德曼-水边的阿狄丽娜");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-思乡曲.wma","理查德 克莱德曼-思乡曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-瓦妮莎的微笑.mp3","理查德 克莱德曼-瓦妮莎的微笑");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-忘却的悲伤.mp3","理查德 克莱德曼-忘却的悲伤");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-威尼斯之旅.mp3","理查德 克莱德曼-威尼斯之旅");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-午后的旅行.wma","理查德 克莱德曼-午后的旅行");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-星空.mp3","理查德 克莱德曼-星空");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-野花.wma","理查德 克莱德曼-野花");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-英雄交响曲.mp3","理查德 克莱德曼-英雄交响曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-永远爱你.wma","理查德 克莱德曼-永远爱你");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/理查德 克莱德曼-致爱丽丝.wma","理查德 克莱德曼-致爱丽丝");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/绿钢琴 乐曲.mp3","绿钢琴 乐曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/马克西姆-克罗地亚狂想曲.wma","马克西姆-克罗地亚狂想曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/马友友-天鹅 大提琴演奏.mp3","马友友-天鹅 大提琴演奏");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/莫扎特 c大调小星星变奏曲.mp3","莫扎特 c大调小星星变奏曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/莫扎特-安魂曲.mp3","莫扎特-安魂曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/莫扎特-魔笛.mp3","莫扎特-魔笛");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/莫扎特-土耳其进行曲.mp3","莫扎特-土耳其进行曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/莫扎特-小步舞曲.mp3","莫扎特-小步舞曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/莫扎特-摇篮曲.wma","莫扎特-摇篮曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/莫扎特-幽默曲.mp3","莫扎特-幽默曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/齐普利安·波隆贝斯库-永恒的记忆.wma","齐普利安·波隆贝斯库-永恒的记忆");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/犬夜叉-哀歌.mp3","犬夜叉-哀歌");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/犬夜叉-跨越时代的思念.mp3","犬夜叉-跨越时代的思念");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/神秘园-莲花.wma","神秘园-莲花");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/神秘园-夜曲.mp3","神秘园-夜曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/神秘园-夜曲.wma","神秘园-夜曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/神秘园-月亮门.mp3","神秘园-月亮门");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/神秘园之歌-月亮门.wma","神秘园之歌-月亮门");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/神思者-Project.mp3","神思者-Project");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/神思者-悲情城市.mp3","神思者-悲情城市");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/神思者-故宫的记忆.mp3","神思者-故宫的记忆");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/神思者-海之女神.mp3","神思者-海之女神");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/舒伯特-圣母颂.wma","舒伯特-圣母颂");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/舒曼-梦幻曲.wma","舒曼-梦幻曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/威尔第 茶花女-普罗旺斯的陆地和海洋.mp3","威尔第 茶花女-普罗旺斯的陆地和海洋");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/乌鸦 片尾曲-月光石 Rurutia.mp3","乌鸦 片尾曲-月光石 Rurutia");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/喜多郎-飞天.wma","喜多郎-飞天");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/喜多郎-菩提树.mp3","喜多郎-菩提树");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/萧邦-幻想即兴曲.mp3","萧邦-幻想即兴曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/徐仁修-森林狂想曲.wma","徐仁修-森林狂想曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/姚斯婷-寂静之声.wma","姚斯婷-寂静之声");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/约翰 施特劳斯-溜冰圆舞曲.mp3","约翰 施特劳斯-溜冰圆舞曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/约翰 施特劳斯-闲聊波尔卡.mp3","约翰 施特劳斯-闲聊波尔卡");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/约翰·施特劳斯-蓝色多瑙河.mp3","约翰·施特劳斯-蓝色多瑙河");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/约翰·施特劳斯-维也纳森林的故事.mp3","约翰·施特劳斯-维也纳森林的故事");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/约纳森-杜鹃圆舞曲.mp3","约纳森-杜鹃圆舞曲");
mkList("http://index.asia.ga/?/music/%E7%BA%AF%E9%9F%B3%E4%B9%90/宗次郎-故乡的原风景.mp3","宗次郎-故乡的原风景");
